version: '3'
services: 
  node:
    container_name: 'yarn'
    build: 
      dockerfile: dockerfile
      context: .
    ports: 
      - '8080:8080'
    volumes: 
      - ./hermit:/app/hermit
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./example:/app/example
    networks: 
      - code-network
networks:
  code-network:
    driver: bridge